baseURL = "http://rfcv.xyz/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Aref N.Z."
theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
footer = "Aref"
description = "Python | Linux | CCNA | AWS Cloud Practitioner"
avatarURL = "/images/profile-pic.JPG"
AvatarAltText = "avatar"
avatarSize = "size-m"
ShowBackToTopButton = true

socialIcons = [
    # { name = "twitter", url = "https://example.com" },
    { name = "linkedin", url = "https://www.linkedin.com/in/aref-anz/" },
    # { name = "stackoverflow", url = "https://example.com" },
    # { name = "dribbble", url = "https://example.com" },
    # { name = "instagram", url = "https://example.com" },
    # { name = "twitch", url = "https://example.com" },
    { name = "email", url = "mailto:aref.anz@outlook.com" },
]

[menu]
[[menu.main]]
name = "Home"
pre = "<span data-feather='home'></span>"
url = "/"
weight = 1

[[menu.main]]
name = "Books"
pre = "<span data-feather='book'></span>"
url = "/books/"
weight = 2

[[menu.main]]
name = "Projects"
pre = "<span data-feather='code'></span>"
url = "/projects/"
weight = 3

[[menu.main]]
name = "Resume"
pre = "<span data-feather='briefcase'></span>"
url = "/resume/"
weight = 4

[[menu.main]]
identifier = "github"
pre = "<span data-feather='github'></span>"
url = "https://github.com/aref-dev"
weight = 5
