baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Aref N.Z."
theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
footer = "Aref"
description = "“The effort to leave the beaten path forces everyone into the same ditch.” ~ René Girard"
avatarURL = "/images/meow.jpg"
AvatarAltText = "avatar"
avatarSize = "size-m"
ShowBackToTopButton = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
pre = "<span data-feather='home'></span>"

[[menu.main]]
identifier = "books"
url = "/books/"
post = ""
name = "Books"
weight = 2
pre = "<span data-feather='book'></span>"

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3
pre = "<span data-feather='code'></span>"

[[menu.main]]
name = "Resume"
url = "/resume/"
weight = 4
pre = "<span data-feather='briefcase'></span>"

[[menu.main]]
identifier = "github"
url = "https://github.com/aref-dev"
weight = 5
# We use feather-icons: https://feathericons.com/
pre = "<span data-feather='github'></span>"

[[menu.main]]
identifier = "linkedin"
url = "https://www.linkedin.com/in/aref-anz/"
weight = 6
# We use feather-icons: https://feathericons.com/
pre = "<span data-feather='linkedin'></span>"
